create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text not null,
  requirement text not null,
  source text default 'website',
  created_at timestamptz not null default now()
);

alter table public.inquiries
add column if not exists address text not null default '';

alter table public.inquiries enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.inquiries to anon, authenticated;
grant usage, select on sequence public.inquiries_id_seq to anon, authenticated;

drop policy if exists "Allow anonymous inquiry inserts" on public.inquiries;
create policy "Allow anonymous inquiry inserts"
on public.inquiries
for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(phone)) > 0
  and length(trim(address)) > 0
  and length(trim(requirement)) > 0
  and length(name) <= 120
  and length(phone) <= 40
  and length(address) <= 500
  and length(requirement) <= 4000
);
