create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text not null,
  usage_type text not null default 'home',
  quantity_required integer not null default 1,
  product_selection text not null default '{}',
  requirement text not null,
  source text default 'website',
  created_at timestamptz not null default now()
);

alter table public.inquiries
add column if not exists address text not null default '';
alter table public.inquiries
add column if not exists usage_type text not null default 'home';
alter table public.inquiries
add column if not exists quantity_required integer not null default 1;
alter table public.inquiries
add column if not exists product_selection text not null default '{}';

alter table public.inquiries enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.inquiries to anon, authenticated;
grant usage, select on sequence public.inquiries_id_seq to anon, authenticated;

drop policy if exists "Allow anonymous inquiry inserts" on public.inquiries;
create policy "Allow anonymous inquiry inserts"
on public.inquiries
for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(phone)) > 0
  and length(trim(address)) > 0
  and usage_type in ('home', 'commercial', 'industrial', 'mixed')
  and quantity_required >= 1
  and quantity_required <= 10000
  and length(product_selection) >= 2
  and length(product_selection) <= 4000
  and length(trim(requirement)) > 0
  and length(name) <= 120
  and length(phone) <= 40
  and length(address) <= 500
  and length(requirement) <= 4000
);

create table if not exists public.broker_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  city text not null,
  experience text not null,
  products text not null,
  message text not null default '',
  source text default 'website',
  created_at timestamptz not null default now()
);

alter table public.broker_leads enable row level security;

grant insert on table public.broker_leads to anon, authenticated;
grant usage, select on sequence public.broker_leads_id_seq to anon, authenticated;

drop policy if exists "Allow anonymous broker lead inserts" on public.broker_leads;
create policy "Allow anonymous broker lead inserts"
on public.broker_leads
for insert
to anon, authenticated
with check (
  length(trim(name)) > 0
  and length(trim(phone)) > 0
  and length(trim(city)) > 0
  and length(trim(experience)) > 0
  and length(trim(products)) > 0
  and length(name) <= 120
  and length(phone) <= 40
  and length(city) <= 120
  and length(experience) <= 2000
  and length(products) <= 1000
  and length(message) <= 2000
);
